[workspace]
resolver = "2"
members = ["packages/ui", "packages/web", "packages/desktop", "packages/mobile"]

[workspace.dependencies]
dioxus = { version = "0.7.1" }
vidyut-lipi = "0.2.0"

# workspace
ui = { path = "packages/ui" }
