[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
vidyut-lipi = { workspace = true }
regex = "1"
tokio = { version = "1", features = ["time", "rt"], optional = true }
gloo-timers = { version = "0.3", features = ["futures"], optional = true }
lazy-regex = "3.4.2"
async-std = "1.12"

[features]
default = []
desktop = ["tokio"]
web = ["gloo-timers"]
